### ISSUE TITLE
Hard coded path in ExecutableDeploder

### ISSUE THREAD

**Issue by Metibor** [Pyrdacor/Ambermoon#1]
The following line leads to the problem mentioned in https://github.com/Pyrdacor/Ambermoon.net/issues/1#issuecomment-672021821

https://github.com/Pyrdacor/Ambermoon/blob/ea4c11c630db107c0cc9796f82ee923423ce86ff/AmbermoonTools/Ambermoon.Data.Legacy/ExecutableDeploder.cs#L54

I think you can safely remove the line, because the Deplode method is already called with the content of AM2_CPU.

**Comment by Pyrdacor** [comment]
Yeah this was a relict of test code. But I just released a new version where I reworked many parts of the executable loader and deploder. You now have methods to load any hunk file (e.g. executable) and the loader will automatically deplode if necessary. You will always get the deploded hunks. There also is the deplode to byte-array method if you need it.

I renamed the class to [AmigaExecutable](https://github.com/Pyrdacor/Ambermoon/blob/master/AmbermoonTools/Ambermoon.Data.Legacy/AmigaExecutable.cs). Some details are guessed by me but it works with AM2_CPU and AM2_BLIT (both imploded and deploded) which I have for testing here.

The class is now static. Best way to read an executable is the new method `public static List<Hunk> Read(IDataReader dataReader, bool deplodeIfNecessary = true)`. You can do almost everything you will need and get a nice list of hunks which provide information about hunk type, size and data. Enjoy! ;)

**Comment by Pyrdacor** [comment]
> 
> 
> The following line leads to the problem mentioned in [Pyrdacor/Ambermoon.net#1 (comment)](https://github.com/Pyrdacor/Ambermoon.net/issues/1#issuecomment-672021821)
> 
> https://github.com/Pyrdacor/Ambermoon/blob/ea4c11c630db107c0cc9796f82ee923423ce86ff/AmbermoonTools/Ambermoon.Data.Legacy/ExecutableDeploder.cs#L54
> 
> I think you can safely remove the line, because the Deplode method is already called with the content of AM2_CPU.

I just now noticed that you related this to the bug in the C# rework. Thanks for that. ;)
