### ISSUE TITLE
No trigger/event with Lady Heidi

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon#10]
Hello,

I don't know if this is already known or I just haven't read it.
When you talk to the cook of Baron George, you should then turn to Lady Heidi with the word "fairies".
She tells that the sylphs took spoons.

Both at Grandpa's and in the Sylphs' cave you will find that silverware, but Lady Heidi does not react to these things.

**Comment by Pyrdacor** [comment]
NPCs are a bit limited. Moreover I guess she would react differently to Grandpa's stuff then to her own. But this can hardly achieved as it's the same item in-game.

Many NPCs do not say anything to stuff they know or should know.

Maybe we can extend this later but I guess it might be a huge effort.

**Comment by skdubg** [comment]
No error in the original game. 
therefore this can closed
