### ISSUE TITLE
Ambermoon v1.08/v1.09 back to disks?

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon#14]
Because @Pyrdacor implemented LOB packing, is it possible to put the v1.08/v1.09 files back into disk images for distribution? 

Do they still physically fit? 

It's just I think it would be easier (for Amiga users) if v1.08/v1.09 were re-distributed as un-installed ADF images.

Previous patches without LOB packing it was impossible to put them back on disks because of the sizes of the uncompressed files.

**Comment by Pyrdacor** [comment]
I packed 1.09 english into ADFs. No problems regarding size. You can find them here as zip, tar.gz and lha: https://github.com/Pyrdacor/Ambermoon/tree/master/Disks/English

Let me know if it fits. I don't know if AMBER_A is still bootable. But I could play the game from disk with WinUAE.

**Comment by Pyrdacor** [comment]
Ok I fixed an issue with ADFOpus on my system and managed to create a bootable A-disk. I repacked all and updated the archives mentioned above.

**Comment by a1exh** [comment]
> I also rescued the ADFOpus project to github as it was an old CVS repo on sourceforge that nobody would maintain anymore.

I think ADFOpus was eclipsed by plugins for Total Commander. Or may ADFView (which I think is incredible even today!).
