### ISSUE TITLE
Ambermoon French

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon#2]
Author dlfrsilver confirms this is the last version of his fan-made French translation of Ambermoon. Dated 11/12/2013.

http://thalion.atari.org/games/ambermoon/amiga/AmbermoonFR_beta111213.lha

> The ending text has to be translated, but I never found how to do it properly.

**Comment by Pyrdacor** [comment]
If english is fixed we might finish the english one. My wife speaks french so maybe I can ask her for help.

**Comment by a1exh** [comment]
I spoke further with dlfrsilver and he tells me the only untranslated part is :
>In the huge crunched Ambermoon_extro file.

Just like AM2_CPU and AM2_BLIT this file is packed with Imploder and once depacked the text is visible. It is possible that the non UTF-8 codes put him off?

> If english is fixed we might finish the french one.

The English v1.07 extro is mainly in English, it has sections still in German. They are quotes from the German developers. Perhaps they remain in German to keep the essence of the quotes? Google translate does an OK job but as I cannot read German I don't know how good they are.

**Comment by Pyrdacor** [comment]
I didn't look at the extro files yet. Didn't know there were texts inside but as you said it, it makes sense. When I have time for it, I'll have a look at the decrunched texts.

**Comment by Pyrdacor** [comment]
@a1exh Recently I decoded the Ambermoon_extro. All the texts are in one Hunk and I can easily extract and reinsert them. So I could provide the text files and could insert the translations if you want.

**Comment by a1exh** [comment]
Yes please. I will send them to the author of the FR version. He is very active and will send a response fast.

**Comment by Pyrdacor** [comment]
[Ambermoon_extro_texts.zip](https://github.com/Pyrdacor/Ambermoon/files/6982640/Ambermoon_extro_texts.zip)

To ease the re-importing it would be best to leave the file numbering as it is. Each text file is a text line. The extro processes lines while scrolling. If you need more info, just tell me.

**Comment by a1exh** [comment]
dlfrsilver has translated the texts. He says the intro and menus are already translated in the FR version linked to above.

http://thalion.atari.org/games/ambermoon/resource/Ambermoon_extro_texts_FR.7z

**Comment by Pyrdacor** [comment]
Great. That was fast. I will re-import them and send you the file tomorrow or on Monday.

**Comment by Pyrdacor** [comment]
@a1exh Ok I managed to create the french Ambermoon_extro. Had to create a Amiga hunk writer and some stuff. It works now.

But the text lines are too long. And the outro font has no glyphs for some french characters I guess. :( Or maybe the encoding is wrong. We have to check with @nicodex research on gitlab and then convert the text files or I just add a temporary mapping for the creation. But I guess first the texts have to be shortened.

![image](https://user-images.githubusercontent.com/8607784/130630537-f225ff68-5620-451b-a6a3-5f2c29a61eee.png)
[Ambermoon_extro.zip](https://github.com/Pyrdacor/Ambermoon/files/7039691/Ambermoon_extro.zip)

**Comment by Pyrdacor** [comment]
Ok it crashes on Amiga (WinUAE) but I think I can fix this.

**Comment by Pyrdacor** [comment]
Hm I think the crash might be caused by the missing glyphs / wrong characters as well.

**Comment by a1exh** [comment]
If you need dlfrsilver to shorten any of the texts. Please give me an approx character limit. I am sure he can do it in short space of time.

**Comment by Pyrdacor** [comment]
Yes I need it. I am not sure but the screenshot give you some hint. I guess 45~47 is a good limit. So let's say 46.
