### ISSUE TITLE
[Bug report] - typo in Clementine's English text

### ISSUE THREAD

**Issue by iancrossfield** [Pyrdacor/Ambermoon#28]
**Describe the bug**
Very minor. When talking to NPC Clementine in the Spannenberg House of Healing, she will speak when asked about "MADMAN."  She says "...do not go into his cellar. Speak to him only through the bars."  From context, 'cellar' here seems a probable typo for 'cell'.

**Expected behavior**
The word should probably be 'cell' instead of 'cellar'

**Screenshots**
![Screenshot from 2022-01-15 14-07-50](https://user-images.githubusercontent.com/8728644/149636332-9020f306-75e5-40c0-ba46-321685874902.png)

**Comment by Pyrdacor** [comment]
Will be fixed in 1.14. I hadn't the time to investigate the Linux tool issues yet. :/
