### ISSUE TITLE
[Change request] timestopper - no feedback

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon#29]
there was already in the original: if you destroy the hourglasses in sansries tempel there is no feedack, a text like "with the help of the time stopper you destroyed the hourglass" would be really great. In my opinion, there is feedback in the game for all other actions, here there is only the visual. 

gab es auch schon im original: wenn man in sansries tempel die sanduhren zerstört gibt es kein feedack, ein text wie "mit hilfe des zeitstoppers zerstörten sie die sanduhr" wäre echt toll. im spiel gibt es bei allen anderen aktionen meines erachtens ein feedback, hier gibt es nur das optische.
![01](https://user-images.githubusercontent.com/95400798/144374759-a77a3c7c-85f7-4345-8fc4-94bc0f4bdeb0.png)
![02](https://user-images.githubusercontent.com/95400798/144374763-1f366394-f593-418f-960c-816262a53ba6.png)

**Comment by Pyrdacor** [comment]
I would go even further. The spots where the hourglasses are should be marked as Special (purple exclamation mark) which disappears when it is destroyed. It's frustrating if you don't know which hourglass was already destroyed. Same for the levers. Especially Sansri's temple can get very confusing and frustrating if you don't know what lever you already pulled.

Moreover the walls which come down have strange effects. The text popups that the wall comes down is also triggered when the wall is already down. The event which let's the wall disappear (move it up) happens without a notification. This feels very strange imo. I would like to improve all this.

**Comment by Pyrdacor** [comment]
And the two Minotaur guards which are triggered through text events feel strange as you can walk to them and nothing will happen. Only when you move further the texts appear. And only the second text actually spawns the real monsters. This needs some improvement as well. It feels bad otherwise.

**Comment by Pyrdacor** [comment]
There is already a text for the timestopper event in the data. But the more I investigate, the more I get the impression that the temple has a bad design or wasn't really finalized.

The mentioned text states that the "quiet humming" stops but there was no text before to tell us about the humming in the first place. Moreover there are two hourglasses almost next to each other. And for both the humming would stop? This doesn't make much sense. One hour glass stops the falling wall in the maze and the other one stops the falling wall at the end of the level. Locating both this close to each other seems a bit off. Most players will just destroy both hourglasses at the same time and only then can proceed from the maze to the rest of the dungeon. So they will never encounter the last falling wall at the end of the level.

Of course I can't redesign the whole level but adding the current message will also be a bit strange. :/ Any suggestions about this?

**Comment by Pyrdacor** [comment]
Here are two maps connected:

![image](https://user-images.githubusercontent.com/8607784/177175868-7243fc9b-c648-4d78-bfce-96e28b0424a4.png)

Hourglasses also marked orange in the lower left. The blueish area is the falling wall which is stopped when destroying one of the hourglasses. Left of the player position there is the second falling wall. Way beyond the maze.

**Comment by Pyrdacor** [comment]
In the last corridor there is a chest behind a fake wall. I think it would be a much better spot for the second hourglass. First the distance to the other hourglass/falling wall is far enough to hear a second humming. And second it is near the falling wall, so you will often encounter it and have to react to it by finding the hourglass. Maybe the chest can be moved to one of the current hourglasses locations. The chest contains a Ring of Luck, Parry Ring and a Aiming Brooch (or whatever it is called in English). They would help against the monsters in the Maze. In my opinion this change would improve the feel of the dungeon a bit. Moreover I would like to change the levers, so that the one behind the falling wall will only open the last wall in the red area.

**Comment by Pyrdacor** [comment]
There is also a possible bug involved. When you destroy the timestopper, the events for the falling wall is disabled. But also the one to move the wall back up. This is solved by triggering the "wall up" event everytime you move over it. But if you use spells like "Word of return" while the wall is down and then destroy the hourglass you won't be able to proceed ever. You could also overjump the "Wall up" event with the Jump spell and destroy the hourglass.

Of course this is a rare edge case but maybe someone in front of the wall will use "Mark of return" to get to the start of the maze etc.

**Comment by Pyrdacor** [comment]
Ok I implemented all the mentioned stuff and tested it. Feels much better now.

**Comment by Pyrdacor** [comment]
In 1.16 all the changes are added. First tests made the feel of the dungeon much smoother and more logical.
