### ISSUE TITLE
Running Ambermoon.net ouside X11 on GNU/Linux

### ISSUE THREAD

**Issue by vanfanel** [Pyrdacor/Ambermoon#3]
Hi there

I just discovered this project via some comment on the Scummvm forum and I am amazed on how awesome this is, Ambermoon is a legend of a game for me!

Now, I only do C coding, so I have never touched anything C#.
So, how does this run on GNU/Linux? I seem to understand that Monogame is the way to go, right? Does that allow to run on SDL2 or some other GLES-driven API that would run outside X11 like SDL2 does on KMSDRM?

**Comment by Pyrdacor** [comment]
Hi. I think the other project is better to discuss this as this repo is only for game data decoding and information. I have answered there. https://github.com/Pyrdacor/Ambermoon.net/issues/78.
