### ISSUE TITLE
Broken portals

### ISSUE THREAD

**Issue by Hexaae** [Pyrdacor/Ambermoon#33]
A few broken portals still left (Lyramion's Islands) with bad tiles on the 2D map at:
X: 283, Y: 253
X: 310, Y:736

e.g.:
![image](https://user-images.githubusercontent.com/8591462/166154902-5df62114-fb81-480a-b305-04006059e860.png)

Can't exactly remember the story since the last time I played Ambermoon... but they should appear restored, because they do work in this old save-game.

**Comment by Pyrdacor** [comment]
If this is an old savegames, this is the issue. The savegames store tile changes so the fix won't affect savegames that were saved before the fixes.

**Comment by Hexaae** [comment]
Makes sense.
Thank you for your dedication to this masterpiece! ❤
