### ISSUE TITLE
Game doesn't start on a 68060

### ISSUE THREAD

**Issue by ProbDenis** [Pyrdacor/Ambermoon#38]
I believe this is actually an old Ambermoon bug. I recently got a TF1260 card, and with this card installed the game doesn't launch anymore and gets stuck on a black screen. It works fine on an 030 accelerator. I was able to reproduce this behaviour in FS-UAE by trying different CPU configurations.

**Comment by Pyrdacor** [comment]
Hi. Which game version did you try?

**Comment by a1exh** [comment]
It is widely known that Ambermoon German v1.00 & v1.01 do not work on 040/060 with caches turned on. 

It was fixed in v1.05 and later.

There shouldn't be issues with 040/060 with the latest release as it is based on v1.07 (the last executable from Thalion)

**Comment by ProbDenis** [comment]
I first noticed it with 1.11, that's what I had installed when I got the accelerator. Then I updated and tried 1.13 (German) with the same results.

**Comment by Pyrdacor** [comment]
Can you try with the original 1.07 version from here: http://thalion.exotica.org.uk/games/ambermoon/amiga/ambermoone.zip

**Comment by ProbDenis** [comment]
I didn't know that! I've been using PFS3 for more than a year now. And before I got the 060 card, Ambermoon definitely worked.

So I just did a test in FS-UAE again. Installed Ambermoon 1.13 on a PFS3 partition. Works with a stock A1200 configuration, but fails with an 060. Interesting.

**Comment by a1exh** [comment]
You could try to change the CPU option which moves the VBR to accelerator fast RAM. There have been rumours that Ambermoon is sensitive to VBR being moved to FastRAM. Just rumours (like above with FFS).

**Comment by ProbDenis** [comment]
One more test: I still had a backup with my previous 1.05 installation, so I tested that one on real hardware. And to my surprise it works perfectly with PFS3 and the 060 accelerator, while 1.13 doesn't. So it's something new?

So at least I can play the game now, but not the updated versions.

**Comment by ProbDenis** [comment]
By the way, could this be related?
http://aminet.net/package/game/patch/amberfix

Though I don't remember if I had this patch installed (probably not, because it never affected me).

**Comment by a1exh** [comment]
> By the way, could this be related? http://aminet.net/package/game/patch/amberfix
> 
> Though I don't remember if I had this patch installed (probably not, because it never affected me).

We've discussed it. That is a fake. The files are identical to v1.05

**Comment by ProbDenis** [comment]
Yeah, and like I said it's very unlikely that I ever installed it, because I wouldn't have had any reason. So I guess whatever causes this error for me, it must be something that was changed after 1.05.

**Comment by a1exh** [comment]
Can you retry v1.11? There was a big change for v1.13

**Comment by ProbDenis** [comment]
1.11 doesn't run either. Is there an archive of all the previous versions? I could just test them one by one to figure out at which version is stops running.

**Comment by a1exh** [comment]
https://github.com/Pyrdacor/Ambermoon/tree/master/Disks/German

**Comment by ProbDenis** [comment]
Perfect, then I'll test all of them later today!

**Comment by Pyrdacor** [comment]
I didn't change anything related to the intro. This is really strange. @a1exh Any idea?

**Comment by Pyrdacor** [comment]
Can you please try version 1.06 from here: http://slothsoft.net/Ambermoon/Downloads/

If this does not work, please try 1.05 which is linked there too.

Thanks.

**Comment by ProbDenis** [comment]
Both don't work when I apply them on a 1.01 installation. But I noticed something interesting. As I said, I simply grabbed my 1.05 update from the WHDLoad package, because according to the readme it includes the necessary files for the update in its "data-de" subfolder.
Now, the 1.05 patch you've linked updates the files **Ambermoon_intro** and **Ambermoon_extro** among others. However, WHDLoad updates one more file: **Fantasy_intro**. And sure enough, replacing that one file from the WHDLoad package immediately makes all the other versions from 1.07 to 1.13 run without problems.

**Comment by a1exh** [comment]
Fantasy_intro is the little fairy animation with the Thalion logo in it right at the start when you first run the game. I normally skip this before anything

We could take a look and see how the file in the WHDLoad slave differs from the one in v1.05 or v1.07 release.

**Comment by a1exh** [comment]
The WHDload patch says it all. 

The fantasy_intro, Ambermoon_intro and Ambermoon_extro need a fix to support Amiga systems where the VBR has been relocated to FASTRAM.

I'd bet money that you have a different configuration between 030 and 060 and this option is turned off in 030 and on in 060?

**Comment by ProbDenis** [comment]
My previous accelerator (an ACA1233) had a config tool where this was an option, and I deliberately had it switched off. The new card doesn't seem to have that option, or I'm not aware of it. So yes, it's very likely that a different configuration is the cause and I must have something installed that moves the VBR and I just wasn't aware.
Of course it would still be cool if this was also fixed in the new Ambermoon versions, if 2 out of 3 files had already been patched.

**Comment by Pyrdacor** [comment]
To save me some time: what am I supposed to do now?

If I get you right it would help to copy the 3 mentioned files from the WHDLoad slave? Is it available in both languages?

Is there more to do? Should I re-source those files and add code changes?

**Comment by a1exh** [comment]
I *think* the German version has been pre-patched but the English version is patched real time after they have been unpacked.

The information about what byte it changes after unpacking are in the source code. Offset 0xFE . Change to $4e71 (NOP)

I don't know how different fantasy_intro is between English and German. Is there any localisation? Are they the same? Maybe you can use the pre-patched version for both English and German?

**Comment by a1exh** [comment]
Look for the comment ";skip getting vbr" for the offsets they change after decompressing.

**Comment by a1exh** [comment]
WHDLoad pre-processor / markup is documented here :

https://whdload.de/docs/autodoc.html

**Comment by ProbDenis** [comment]
I hadn't tested the English version, so I did that now. It seems to be patched correctly, at least for me it works fine. In the German version, it's only fantasy_intro that fails. So I can actually copy the file from the english 1.14 version over to the German 1.13 and it will run. The two animations are identical and there's no localization.

**Comment by a1exh** [comment]
I think this can be closed now? Fixed in v1.15?

**Comment by Pyrdacor** [comment]
I would like someone to verify this. If so it should have been fixed in German 1.14 already.

**Comment by ProbDenis** [comment]
I can confirm that it works for me now, both on real hardware and in emulation.

**Comment by Pyrdacor** [comment]
Thanks. Closing this now.
