### ISSUE TITLE
Chairs are bugged in Pelanis' palace

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon#40]
![image](https://user-images.githubusercontent.com/8607784/174600791-be1137f7-fa61-491c-a146-5d99e250b761.png)

**Comment by a1exh** [comment]
Sprite priority issue? Emulation settings? 

Or you think this is in the map data?

**Comment by Pyrdacor** [comment]
I guess there is not much we can do about it unless we adjust the chair sprites. If it's ok, I will leave it as it is. Nobody complained about it yet.

**Comment by macce2** [comment]
![corridor](https://github.com/Pyrdacor/Ambermoon/assets/116389369/cb34d4ab-471f-40f2-96d8-b08b8b0f9a40)

Excuse me, but just one more example picture of the problem here
