### ISSUE TITLE
Pelanis is still named Pelani (the NPC), at least in german

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon#41]

**Comment by a1exh** [comment]
Definitely worth fixing. 

We had [our discussion](https://github.com/Pyrdacor/Ambermoon.net/issues/52#issuecomment-867401839) about whether it should be PELANIS or PELANI reasoning that there were more occurrences of one than the other.

@kermitfrog then mentioned that PELANIS is actually a recurring character from Amberstar (I probably knew but I had forgotten).

https://www.youtube.com/watch?v=NGiJll56Dnk

PELANIS' age in Amberstar is 896, does he have an age in Ambermoon? Do we know approx how many years the two episodes are supposed to be set apart? Just curious if it is consistent.

**Comment by Pyrdacor** [comment]
His age is 721 in Ambermoon so he seems to be younger now. :D
