### ISSUE TITLE
Unused Text : NPC Drongeb

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon#42]
The following string associated with character "Drongeb" seem to have no event trigger

"DOREB, THE LANDLORD OF DOR KIREDON, ACTUALLY SUCCEEDED IN BREWING AN ENJOYABLE TYPE OF ALE FROM THE PLANTS GROWING AROUND HERE. WHAT ELSE DO WE NEED?"

Possibly related to NPC_texts.amb 034.amb

"WE HAVE MANAGED TO BREW SOME REAL DWARF ALE FROM A FEW OF THE PLANTS HERE. THIS IS OUR FAMILY SECRET. TRY SOME!"

**Comment by Pyrdacor** [comment]
I investigated this and found that there is another text for Drongeb which can't be shown: "WELCOME! HOW NICE TO SEE YOU AGAIN!" This is text id 006 of NPC_texts.amb sub-file 059. It should be shown when talking to Drongeb for the second time. This is controlled via global var 67. But it isn't set. I will add it.

**Comment by Pyrdacor** [comment]
Done

**Comment by Pyrdacor** [comment]
Should be fixed in 1.16
