### ISSUE TITLE
Unused Texts : NPC Gorban

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon#44]
"I OWE HIM MY LIFE! I AND MY FAMILY ARE DEEP IN HIS DEBT." - NPC_texts.amb : 043.amb

**Comment by Pyrdacor** [comment]
From context this would be the reaction when you say "Asrub" as he is the healer who saved him. But there is no such entry in the dictionary. I could add it but the text has not much value and there is no hint that this name would have any reaction. What do you think @a1exh ?

**Comment by a1exh** [comment]
I think we just forget it. I had no context when I wrote this. Just that it had been reported
