### ISSUE TITLE
Unused Text - NPC Sandra

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon#45]
"I CANNOT THANK YOU ENOUGH FOR RELEASING MY DAUGHTER FROM THE CLAWS OF LUMINOR. SO I HAVE ASKED FATHER ANTHONY TO SUPPLY YOU AT HALF THE NORMAL RATES." - NPC_texts.amb : 005.amb

**Comment by Pyrdacor** [comment]
This would be used if global var 27 would be true and you talk to Sandra. I think var 27 is "has defeated luminor" or "has freed the Burnville people". When you open the cage in the basement of Luminor's tower there is already a global var set (32). It is for example used to change what Sabine says when you talk to her. As the global var 27 is never set in Ambermoon I now set it after opening the cage as well. This way Sandra should then use the missing text. The change was added to map 293 in 2Map_data.amb.

**Comment by Pyrdacor** [comment]
Should be fixed in 1.16
