### ISSUE TITLE
Unused Texts : HOUSE OF THE HEALERS - BURNVILLE

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon#48]
@prophesore [reported](http://eab.abime.net/showpost.php?p=893740&postcount=536) three strings at this location he was never able to get to appear

`IN THE BED BEFORE YOU LIES A MAN WITH SEVERE BURNS. HE MURMURS:^ "HOW CAN I EVER THANK YOU FOR FREEING ME FROM LUMINOR'S PRISON? A FEW DAYS LONGER AND I WOULD HAVE JUST BEEN A PILE OF ASH.`

`BEFORE YOU LIES AN OLD WOMAN IN BED. ALMOST ALL OF HER BODY IS WRAPPED IN BANDAGES. HER FOREHEAD IS WET WITH PERSPIRATION AND SHE JABBERS AND CRIES DELIRIOUSLY:^ "NO, PLEASE, NOT THE RED HOT HOOK, NO, NO, NO!" PLEASE, YOU CAN TELL LUMINOR THAT I WILL NEVER SPEAK AGAINST HIM EVER AGAIN AND WILL ALWAYS BE HIS SLAVE, IF YOU JUST STOP THIS TORTURE." PLEASE, PLEASE.....!!"`

`A YOUNG HEALER COMES RUNNING TO HER BED AND TAKES THE WOMAN'S HEAD LOVINGLY IN HER HANDS. SHORTLY AFTERWARDS THE OLD WOMAN QUIETENS DOWN AND APPARENTLY FALLS ASLEEP. THE HEALER SMILES AT YOU AND SAYS:^ "OLD MERIL SUFFERED BADLY IN LUMINOR'S PRISON. IT WILL TAKE A LITTLE LONGER FOR HER TO BE ABLE TO LEAD A NORMAL LIFE AGAIN. BUT THAT IS STILL BETTER THAN DYING AT THE HANDS OF LUMINOR.^ THANK YOU AGAIN FOR RELEASING US.`

https://gitlab.com/ambermoon/research/-/wikis/Amberfiles/Map_texts - 286.003

Maybe these have been fixed too following the fix for bug #45 with global var 27 now being set?

**Comment by Pyrdacor** [comment]
There are 3 NPCs on that map (beside Sabine). But I guess they are not "activated" after freeing them in Luminor's tower. NPC activation is independent of global variables. Each NPC, monster or party member has its own bit inside the savegame which can be changed by an event. I will add those events.

**Comment by Pyrdacor** [comment]
I spoke too soon. The NPCs are activated and I can find them in Burnville in the house of the healers.

**Comment by Pyrdacor** [comment]
Someone should verify but on my end this works on Amiga. The remake has issues here but this is of different nature.

**Comment by a1exh** [comment]
So the feedback is that this was bad bug report and these texts were accessible in v1.07?

**Comment by Pyrdacor** [comment]
I can only say that the NPCs can be activated in 1.15 and I don't have changed anything related. I can test a bit more but it looks good in data.

**Comment by Pyrdacor** [comment]
I checked Let's Plays from 4 years ago and the NPCs are there as well. So the report is either wrong or only bugged in english as I only checked German.

**Comment by Pyrdacor** [comment]
English had them too. But there is one issue. Two of them are in bed. Ambermoon won't show texts for sleeping NPCs but instead show the message "this person is sleeping". If a NPC is sleeping is determined by the tile flags the NPC is on. If it is a bed, the NPC is considered sleeping. And as those NPCs won't move, you can't see the real texts. There is an exception to this. A NPC can have the flag "use tileset". In this case the NPC is rendered by a tile graphic and not an NPC graphic. This is used by grandpa for example. This allows using the text. But the NPCs in this case use normal NPC graphics which is odd as they will always lie in bed and NPCs in bed always use the same sprite (the same as the player in bed).

I guess the right fix here would be to use the tileset like for grandpa or Sally. There is especially a tile graphic for sick people in bed. This was you could also talk to them.

**Comment by Pyrdacor** [comment]
I only noticed now that you only posted two messages. The last one looks like 2 texts but it is actually only 1 in the text list. It is a very long text.

So actually 2 texts could not be triggered. And the reason is that you can't talk to sleeping persons as mentioned. I will add the flags to the two NPCs and then the texts should be available.

**Comment by Pyrdacor** [comment]
I fixed it now. You can talk to the two patients and trigger the texts.

**Comment by Pyrdacor** [comment]
Should be fixed in 1.16
