### ISSUE TITLE
Missing Race name for animal NPCs

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon#49]
@Pyrdacor wrote [on twitter](https://twitter.com/Pyrdacor2/status/1487136450948878337) that he had found a bug which leads to missing race names for animal NPCs.

> There are 16 race names. Race 13 is animal and 14 is monster. But there seems to be a bug as the animal text is in slot 14. So if you talk to the only animal NPC in the game "Necros" he has no race name.
The race strings are one off at the end so that the mapping is wrong. Should be a really easy fix by moving a zero byte around.

Did this ever get fixed? Presumably it was inside AM2_CPU/AM2_BLIT which you've now consolidated?

**Comment by Pyrdacor** [comment]
I just tested and it is still not displayed. I will have a look at it later.

**Comment by Pyrdacor** [comment]
It seems like I have just moved the texts over as they were (including the wrong animal race text offset). Will fix this now.

**Comment by Pyrdacor** [comment]
Should be fixed in 1.16
