### ISSUE TITLE
Tower 2D movement issue

### ISSUE THREAD

**Issue by Hexaae** [Pyrdacor/Ambermoon#51]
![image](https://user-images.githubusercontent.com/8591462/177818561-e8f89b83-9e35-47dd-9022-e63bfbd3298a.png)

From my advanced savegame, when I teleport to this isle and try to enter the tower (Lebab's Tower if I remember correctly) the 2D sprite enters the tower for at least 2 blocks before it stops.... Long time since I completed this part, but as far as I can remember you can't enter the Tower anymore after you completed the sub-quest so this should be fine. Not sure, but what's wrong is the sprite movement "into" the door...

**Comment by Hexaae** [comment]
> @Hexaae Can you send me a savegame from before that door please?

In this comment, MEGAHERO saving, just enter the first portal from top-left.

**Comment by Pyrdacor** [comment]
I finally had time but the file in the linked comment only has one single savegame where you are at grandfather's house.

**Comment by Pyrdacor** [comment]
But I could reproduce by my own now.

**Comment by Pyrdacor** [comment]
The door event which usually appear is working fine with new savegames. Somehow it got deactivated in your savegame. Is this an older one?

**Comment by Pyrdacor** [comment]
There is no event in the game which is able to deactivate the door event. At least anymore. Maybe there was back in the days before I reworked the world map doors. So this should be fixed for all new savegames.

**Comment by Hexaae** [comment]
The door works fine. Once you complete the quest you can't enter the tower anymore as far as I can understand. Only from that moment on, there was the issue of your sprite moving inside the tower.
Expected behaviour: stop in front of the door, your sprite shouldn't disappear into the tower.
P.S. I updated the savegame file above. Please test the Megahero savegame, and enter the first portal in the upper left.

**Comment by Pyrdacor** [comment]
There is no reason why you should not be able to enter the tower afterwards. In contrast it would even be a bug as you couldn't access the enchantress anymore.

What do you mean by "complete the quest"? Talk to Lebab?

**Comment by Hexaae** [comment]
Yep, there was something to do to talk with Lebab AFAICR... So it was probably a bug... argh... is there a way to fix a savegame? A guide or a tool...? I'd like to continue my game since I was at 50% already :(

**Comment by Pyrdacor** [comment]
Sure it is easy to fix. I will post the hex fix in a minute.

**Comment by Pyrdacor** [comment]
If you copy this to your Save.01 folder it should work. **Please make a backup!**

If you want to manually fix it you have to Un-JH the file first or start the game, load the savegame and then use the Party_data.sav from the main folder ("Amberfiles/"). Then open it with a hex editor and go to offset 0xAC4. There should be a byte with the value 30 (hex). Change it to 10 (hex) and the door should work again. You can leave the file unencrypted. Make sure you copy it back to the right savegame slot. I guess it is the first so "Save.01".

[Party_data.zip](https://github.com/Pyrdacor/Ambermoon/files/9363203/Party_data.zip)

**Comment by Hexaae** [comment]
Thank you!
It worked, but for some strange reason the first time I approached the door from exterior I had to fight against gargoyles in the forest (???):
![WinUAE Screenshot 2022 08 17 - 17 14 55 19](https://user-images.githubusercontent.com/8591462/185180373-149562b6-74ba-46b6-aa71-5de55cce8b45.png)

May I ask you another favor? Is the fixed game supposed to have the teleporters buggy like this (wrong/missing tile) in this two locations (see coords)?
![WinUAE Screenshot 2022 08 17 - 17 24 51 22](https://user-images.githubusercontent.com/8591462/185180736-2cb9a4e5-ce50-4fe3-85db-4e75ef422279.png)

![WinUAE Screenshot 2022 08 17 - 17 24 28 28](https://user-images.githubusercontent.com/8591462/185180749-d16f1c3b-3da8-494d-b3b3-ba96a6a6e35b.png)

**Comment by Pyrdacor** [comment]
It's normal to fight them in the forest as they come out of the tower as the message states.

The tiles were fixed but tile changes are stored in the savegame as well. So if this savegame is old, the bugged tiles are still there. This should not happen with new saves though. Fixing those in your savegame is a bit harder though and I won't have the time for that I fear.

**Comment by Hexaae** [comment]
Ok, never mind.. I hoped it would be enough to change a couple of bytes for the new tiles ;)

**Comment by Pyrdacor** [comment]
In theory yes but find the right bytes and the correct new values is a bit of work as you have to find out which tile change events are associated to that portals, and which tile indices are the correct ones. This will cost at least half an hour or more and I don't have the time for that. Sorry.
