### ISSUE TITLE
Valdyn and Sylphe 'goodbye' text should be updated

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon#6]
Valdyn:

![048](https://user-images.githubusercontent.com/5891591/129172672-3514d2ea-6960-401b-9555-884af0959734.png)

He is at the Luminor's Tower:

![049](https://user-images.githubusercontent.com/5891591/129172680-4e49cc7c-9d69-41ff-997a-cefe56a93711.png)

Sylphe:

![050](https://user-images.githubusercontent.com/5891591/129172794-9ec1d12a-8d2c-48b7-9527-bdb4e365afbb.png)

She is at the Orc Cave:

![051](https://user-images.githubusercontent.com/5891591/129172798-5695d35c-50f4-48ee-b1db-44cdf172ae84.png)

**Comment by Pyrdacor** [comment]
Hm this is a bug then because they should appear at the locations they mention. The texts are right.

I will investigate this.

**Comment by Pyrdacor** [comment]
Do you test with remake or Amiga version?

**Comment by Uukrull** [comment]
Both. The screenshots are from the Amiga version.

**Comment by Pyrdacor** [comment]
Would be interesting if this also happens with a new savegame on the Amiga without using the remake. I mean using the remake for teleporting should not hurt. But don't talk to the NPCs in the remake.

**Comment by Uukrull** [comment]
That's what I did as you can see in the screenshots: all the talking is done in the Amiga version.
Anyway, it makes sense Valdyn and Sylphe are in the same place where you met them for the first time, as the rest of the characters.
That's the reason I suspected it is a problem with the text and not the location.

**Comment by Pyrdacor** [comment]
The characters store their default return location. This should be ok for Valdyn and Selena. There was a bug where the value for Gryban was invalid so he vanished forever.

What game data version do you use? Can you send me the Save.XX folder and also the Save.00 folder please?

Does it work in the remake with the built-in versions?

**Comment by Uukrull** [comment]
> What game data version do you use? Can you send me the Save.XX folder and also the Save.00 folder please?

1.08 + bugfixing with the remake and WinUAE

[Selena.zip](https://github.com/Pyrdacor/Ambermoon/files/6978616/Selena.zip)
[Valdyn.zip](https://github.com/Pyrdacor/Ambermoon/files/6978618/Valdyn.zip)

> Does it work in the remake with the built-in versions?

With the latest release from github and the 1.08 built-in happens the same:

![98](https://user-images.githubusercontent.com/5891591/129271460-036bb8c3-5684-485b-a29d-69ec4c77ca4a.png)

![99](https://user-images.githubusercontent.com/5891591/129271475-cb0c110c-a80a-4f85-806e-00f6e9f175b8.png)


![100](https://user-images.githubusercontent.com/5891591/129271715-94eeaded-4fa3-4b41-bdba-41b575f3c08f.png)

![101](https://user-images.githubusercontent.com/5891591/129271723-ce2c0ae5-914a-4ec2-b9a3-32a7043a702b.png)

**Comment by Pyrdacor** [comment]
In the remake there was an issue where the spawn location was set to the current location when starting a conversation. This is why every party member spawned on the same map. It is now fixed in the remake and Valdyn for example really spawns in the guest rooms of the Cactus Inn in Burnville.

If this doesn't work in the Amiga version, this is a bug. The data has the values set correct. Maybe the original code ignores it. But I doubt it, as the value seems to be used. Gryban for example has a bugged value in data and it seems to be used.

I will test this with the Amiga version now.

**Comment by Pyrdacor** [comment]
Ok I tested it on Amiga and it works there as well. So either your initial savegames (Save.00) were corrupted or you talked to Valdyn in the remake at least once with the unfixed version.

**Comment by Pyrdacor** [comment]
It does not work with your saves so they are corrupted but the Save.00 is ok. This can only mean that you used Save.01 in the remake and talked to Valdyn. It is enough to talked to him regardless of if you asked him to join or leave.

**Comment by Uukrull** [comment]
I tried the save from [this](https://github.com/Pyrdacor/Ambermoon.net/issues/129) bug report and Valdyn isn't at the Luminor tower anymore when you dismiss him, on both WinUAE and the remake.

**Comment by Pyrdacor** [comment]
So it works now?

**Comment by Uukrull** [comment]
Yes.
