### ISSUE TITLE
Spider book in Grandfather House correction of "WHO HAS AN .OR.H"

### ISSUE THREAD

**Issue by Hexaae** [Pyrdacor/Ambermoon#67]
It should be "WHO HAS A .OR.H" (AN -> A)
![WinUAE Screenshot 2022 08 24 - 17 38 08 84](https://user-images.githubusercontent.com/8591462/186478217-e7d25f2f-89f9-4a68-97b1-5446b29f38e2.png)

**Comment by Hexaae** [comment]
@Pyrdacor 
BTW, how is text.amb compressed and how do I de/repack it? Tried with Amiga tool ExtractAMB but says it's not an AMB...

**Comment by Pyrdacor** [comment]
Here on my GitHub page. Download the tools zip.

The easiest way is to use the tool AmbermoonTextImport.

Windows:
`AmbermoonTextImport.exe -e . 2Map_texts.amb Output\Folder\Path`

Linux:
`./AmbermoonTextImport -e . 2Map_texts.amb ./output/folder/path`


This way for each map a sub-folder is created and each text file within is a map text.

Also works for NPC texts, Party texts and Object texts.

You can later use `-i` instead of `-e` to reimport the texts into the amb files. It you create new text files, you should use the right encoding. Best copy an extracted text file and rename and edit it.

**Comment by Hexaae** [comment]
Ok, but, can't someone provide AmigaOS 3.x+ binaries too?

**Comment by Pyrdacor** [comment]
Those tools won't run on AmigaOS.

You will need to download the NET6 Runtime to be able to run it.

**Comment by a1exh** [comment]
You don't have the Amiga tools anymore? I can send them if you prefer them

**Comment by Hexaae** [comment]
> You don't have the Amiga tools anymore? I can send them if you prefer them

Found them but can't uncompress JH files AFAIK...

**Comment by a1exh** [comment]
Decrypt JH files using amcode on aminet?

**Comment by Hexaae** [comment]
Partially working but leaves some bytes at the beginning:

[url=https://postimg.cc/dk4Zr377][img]https://i.postimg.cc/dk4Zr377/image.png[/img][/url]

**Comment by a1exh** [comment]
You've decrypted. Now you need to decompress with xfd

**Comment by Hexaae** [comment]
Yes I use xfddecrunch for LOB files, but in this case won't work if I don't remove the header "JH+2 bytes". Moreover once xfddecrunched, after I remove the bytes, it won't extract sub-files (it seems there are at least 4 different sub-files in it).

I don't think JH compression was used in the original game... so there are no native tools to handle these Ambermoon files under AmigaOS.

**Comment by Pyrdacor** [comment]
JH was used often in Ambermoon.

**Comment by Hexaae** [comment]
Do you know JH tools for the Amiga?

**Comment by Pyrdacor** [comment]
JH is also used in some container formats like AMNC or AMNP. The savegames use JH as well. And I think stuff like the dictionary etc.

**Comment by Pyrdacor** [comment]
See here: https://github.com/Pyrdacor/Ambermoon/blob/master/Files/FileTypes.md

I could write some tools for the Amiga if needed.

**Comment by Hexaae** [comment]
Ok, thanks. Because with Amcode and ExtractAMB, InsertAMB on the Amiga I was able to decrunch/extract/reinsert modified files, but can't handle now files like text.amb which is a JH stand alone.

Would be great a small tool for Amiga too thanks! :)

**Comment by Pyrdacor** [comment]
Text.amb and others use JH+LOB. First decrypt, then skip the header an UnLOB.

**Comment by Hexaae** [comment]
text.amb
I did:
- amcode text.amb -> text_unc.amb: it worked but leaves some JH+2bytes in the header
- removed the 4bytes and xfddecrunched text_unc.amb: it worked but it seems to me there are more than 1 file merged in a single file so I don't know how to extract the single parts...

A straightforward JHdec tool would help IMHO for files like text.amb on the Amiga.

**Comment by Hexaae** [comment]
> Text.amb and others use JH+LOB. First decrypt, then skip the header and UnLOB.
> 
> This is used for non-container files which only represent one file.
> 
> AMNP is a container which uses JH+LOB the same way but for each subfile.

Ok, so pass 1 & 2 described above is enough and there's nothing more to do on text.amb (annoying the manual editing to remove the JH 4 bytes in the header anyway)?

**Comment by a1exh** [comment]
What you're describing must be new. A consequence of @Pyrdacor extracting all the text from the exe to aid in localisation

**Comment by Pyrdacor** [comment]
Text.amb is not a "normal" text container which can be simply extracted to text data files. It is a custom format I invented to store all the exe strings. So in your case you end up with a single binary file of that format. I have a tool to extract the texts.

But what do you want to do with those exe texts? I guess you want the map or NPC texts instead.

**Comment by Pyrdacor** [comment]
About the JH header. Yeah it's annoying. The tool should consider optional LOBs inside JHs as this is used in Ambermoon.

I plan to port my tools (at least those with a CLI) to the Amiga as well in the near future.

**Comment by Pyrdacor** [comment]
Fixed in 8dfd5b4eb3d338562c9dcae45b8c65d1af88233f
