### ISSUE TITLE
Fix broken event chains

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon#70]
- [x] Map 343 (Dor Kiredon): Connect event 0x1b to 0x1a. There is an event where two Gizzeks climb over the town walls to attack you. Event 0x1a is the dice roll event (7% chance). Events 0x1b and 0x1c are then the text box and the battle event. The text and monster groups are also there.
- [x] Maps 440 and 454 (Morag hangar): Connect event 5 to 4. Event 6 must be connected to 5 (currently 6 is connected to 4). This will ensure that the music is reverted to default after the text about the teleport to the prison is shown. In general if a special event happens, the music is changed, text is shown, music is reset. Here the event for music reset is there but not connected. I guess as the following teleport will also change the music. So either remove the music reset event (index 5) or connect it. For me it would be cleaner to connect it.
- [ ] Map 347 (Dorina's cave lower level): Connect event 9 to 8. There is a flame which shows the text on contact but does not hurt. With this fix the flame will hurt again.

**Comment by a1exh** [comment]
I see the first two bugs have been fixed and committed. 

132e56a917446bf647c48dc12a34d0f72cce800e
909cee8d183a9ac26ce8a6694924a56550daa067

**Comment by Pyrdacor** [comment]
Right. I added checkboxes here just now. It is a bit messy at the moment as I find most of them while working on Ambermoon Advanced and then have to fix it in both game versions and languages. Sometimes I do it right away and sometimes I only make a note as I am involved in other stuff.

**Comment by Pyrdacor** [comment]
The third one is fixed in 7f5137ca14b771ca3ef2a8ca9d4db8e937c974ef
