### ISSUE TITLE
Typos in 'liesmich.txt' inside 'ambermoon_german_1.07_extracted.zip'

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon#8]
hi,

another batch of typos found.
number of the entry (correct words marked as bold/italic):

- [1] Sansrie's Schlüssel funktioniert nun in Sansries **_(Sansrie's_)** Tunnel.
- [2] ...als Partymitglied erscheint is **_(ist)_** nun...
- [3] Reg der Hügelriese is **_(ist)_** nun korrekt als Boss gekennzeichnet, so dass **_(sodass)_** er...
- [4] Zwei Teile der Lyramion Weltkarte wurden gefixt, so dass **_(sodass)_** dort...
- [9] Alle Pflanzen auf Kire's Mond wurden behoben, so dass **_(sodass)_** man...
- [10] Ein Text-Popup in Nalvens **_(Nalven's)_** Magieschule wurde behoben, so dass **_(sodass)_** es nun...
- [11] Im geheimen Thalion Büro wurden zwei fehlenden **_(fehlende)_** Text-Popups hinzugefügt.
- [13] Der Start **_(Stadt)_** S'Angrila wurde eine Bodentextur hinzugefügt.
- [14] Die Blickrichtung wurde korrigiert, wenn man in Luminors **_(Luminor's)_** Turm von  Ebene 4 auf 3 wechselt.

**Comment by Pyrdacor** [comment]
I know that the german map names used the apostrophe but this is actually wrong german. But as these are map names I guess the changes are ok. The rest is of course right. Will fix this when I have a time slot.

**Comment by skdubg** [comment]
I also thought about the apostrophe. I am not really familiar with the rules. 

I have found at Wikipedia: 
The apostrophe may not be used to separate the genitive s. The apostrophe is only permitted to clarify proper nouns:
Christina's Blumenshop"

 I have set this equal to "Sandra's Schlüssel", "Luminor's Turm",...

**Comment by Pyrdacor** [comment]
Isn't that example exactly the genitive s? I know in Germany many shops etc use the apostrophe but it isn't right. It's sometimes called "Idiotenapostroph". But it's slang I guess. Nevermind I will just change it as the map is called that way.

**Comment by skdubg** [comment]
Nach der reformierten Rechtschreibung darf der Apostroph beim Genitiv verwendet werden, um die Grundform eines Personennamens zu verdeutlichen. Im Normalfall wird jedoch kein Apostroph beim Genitiv-s verwendet.

Beispiele:

Andrea’s Friseursalon (richtig) – zur Abgrenzung vom Männernamen „Andreas“

Willi’s Würstchenbude (richtig) – zur Abgrenzung vom englischen Männernamen „Willis“


i think Ambermoon and Thalion are not a "Normalfall" 😁🤗

**Comment by Pyrdacor** [comment]
I fixed all of them in the most recent releases. ;)
