### ISSUE TITLE
Weapon levels

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon#80]
There are some weapons which have strange magic weapon levels. The first weapons in the game all have weapon level 0, the most powerful weapons on Lyramion have weapon level 2 (dwarf and elven weapons). And some like the Scimitar have weapon level 1. Then on Kire's moon and Morag you can find weapons of level 3 (Ferrin's crossbow, Morag weapons, etc).

But the following weapons have levels which don't fit into the game progress.

- Zweihander: Has only level 0 but is relatively powerful (similar weapons like Firebrand have higher levels). When you can find it, it is almost useless. Would increase it to 1.
- Holy Sword: Start item of Gryban. Also has level 0 which is way too low when you find him. Should be higher. But as the weapon isn't that good damage-wise I would just increase it to 1 which is the main weapon level on Lyramion.
- Trident: Even more powerful than Zweihander and also has level 0. Would increase to 1.
- Crossbow: Pretty useless with its level of 0. It is also the only crossbow in the game and you can't hit anything with it. Should be 1 to be useful on Lyramion.
- Mando’s Sword: Also level 0 even though it is quite good and even a special weapon. It should at least be 1, but I would even give it a 2 as it is a special item and should be useful in later game I guess.
- Murderer's Blade: Thieves are not that strong and limiting the only strong weapon to level 0 is not so good imo. I would give it level 1 as well to make it a bit more useful. This is even a quest reward.
- Firebrand: This is a cool early weapon but it has a level of 2 which is a bit too high imo. Should be also 1. In current state this is much better as all the above weapons when it comes to weapon level. But on the second island you find a much more powerful Scimitar which only has level 1.
- Valdyn’s Schwert: Yeah this is a special item but I guess level 1 is ok, so you will swap it in Lyramion late game and make other weapons useful as well. It has a weapon level of 3 at the moment!
- Keule der Gala: Even though healers have not much items, I would lower the level from 2 to 1 as there is no logic that a healer's club is so powerful. Healers can use dwarf slings in later game which have level 2 and then later Morag darts.
- Scimitar: It is very powerful and expensive. This is often used still in late game on Lyramion, so maybe it should have level 2 instead of 1.

**Comment by Pyrdacor** [comment]
Adjusted in ae1c0a5cf2b0eef46de545b6f5877b3c49708700

**Comment by macce2** [comment]
It seems that Gryban is actually surprisingly weak with his Holy sword.
IMHO that should be adjusted.
