### ISSUE TITLE
Possible bug(-s) near the Alchemist Tower

### ISSUE THREAD

**Issue by macce2** [Pyrdacor/Ambermoon#83]
Party suffers energy loss near the tower of alchemist
 (northside); there appears not any condition on the character statistics  screen.

  After some party members died there; when trying to quit the game,
  a crash with reboot.
  Couldn't repeat the crash.

After leaving the alchemist tower the second time; graphics corrupted on the
main view screen 2D.

**Comment by Pyrdacor** [comment]
Fixed in c3e51a12415c7cff7bc5cc17fbff867c45d44a1a
