### ISSUE TITLE
Issue with the version launched of AM2_CPU

### ISSUE THREAD

**Issue by dlfrsilver** [Pyrdacor/Ambermoon#89]
The game is launched systematically in version A500. The enhanced mode for the A1200 + turbo card is greyed out.

I have an A1230@50mhz, and i don't have the ceiling 3D and the ground in 3D, only the walls.

Is it a bug or the A1200 version was left out when merging AM2_CPU and AM2_BLIT ?

Thanks for the answer :)

**Comment by a1exh** [comment]
Can you provide some more information? Which version of Ambermoon did you try? (i.e. English/German/French? v1.17?)

The original Ambermoon runs a speed test to determine what CPU you have. If it is fast enough it used AM2_CPU which uses the CPU to draw and includes ceiling and floor support. If it is not fast enough it used AM2_BLIT which uses the blitter to draw and I believe does NOT have ceiling and floor support.

When AM2_CPU and AM2_BLIT were merged into a single binary (1.14) there was a discussion (between @Pyrdacor and Nico) about which file this test is in, how it worked and how it would work for a single binary. I *think* the test was in the file "Ambermoon" in the root directory.

**Comment by a1exh** [comment]
Maybe this file "[Ambermoon](https://github.com/Pyrdacor/Ambermoon/blob/master/Disks/Bugfixing/French/Ambermoon)" has not been updated for the French release and so it defaults to Blitter version?

Try using the file "Ambermoon" from either the [English](https://github.com/Pyrdacor/Ambermoon/blob/master/Disks/Bugfixing/English/Ambermoon) or the [German](https://github.com/Pyrdacor/Ambermoon/blob/master/Disks/Bugfixing/German/Ambermoon) version?

**Comment by dlfrsilver** [comment]
Hi,

Will do this evening after work. But strange, because Robert prepared me
the archive I used.

So I will see if there is a change by using the small ambermoon 9kb file
that do the calculation.

Le jeu. 23 févr. 2023 à 11:27, Alex Holland ***@***.***> a
écrit :

**Comment by Pyrdacor** [comment]
I checked and the "Ambermoon" file I added to the french release is a copy of the english 1.17 one. In Ghidra the arguments are passed. So it should work.

There are two things that come to mind:
- It never worked for the english version as well
- You use the wrong Ambermoon exe or WHDLoad etc messes something up

It is crucial to use the updated Ambermoon exe I provided in the zip.

Maybe to rule out the second point you can test without WHDLoad and just use the files as I sent them. Maybe you already did. But if not, please try this first.

If the behavior persists, I will have a closer look.

**Comment by Pyrdacor** [comment]
At least in WinUAE I can enable the 3D floor and ceiling textures with the version I sent you.

If I use A1200 with good specs both options are available. If I use A500 with bad specs both options are disabled. So this works fine in an emulator.

**Comment by dlfrsilver** [comment]
I have installed your archive fixed. I met the problem out of whdload. I will test under whdload. Envoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [Pyrdacor/Ambermoon] Issue with the version launched of AM2_CPU (Issue #89)De : Pyrdacor À : Pyrdacor/Ambermoon Cc : dlfrsilver ,Author 
At least in WinUAE I can enable the 3D floor and ceiling textures with the version I sent you.
If I use A1200 with good specs both options are available. If I use A500 with bad specs both options are disabled. So this works fine in an emulator.

**Comment by dlfrsilver** [comment]
Issue fixed by taking the Ambermoon small file from the UK v1.17 package.

I have now access to the version for A1200.

Can you upload and fix accordingly Robert ? 

Thanks :)

**Comment by Pyrdacor** [comment]
Done. I uploaded all the most recent packages and files.

- Release Packages: https://github.com/Pyrdacor/Ambermoon/tree/master/Disks/French
- Single files for later bugfixing etc: https://github.com/Pyrdacor/Ambermoon/tree/master/Disks/Bugfixing/French
