### ISSUE TITLE
Fix the boot loader

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon#91]
When installing from the disks the game crashes. I guess the boot loader needs fixing for the merged exe and data externalizations so that the installation works.

**Comment by a1exh** [comment]
Is there any chance to find the bug in the HD installer so that we can install from ADF images again? 

It's the biggest outstanding Amiga bug left now. 

If you need help (because you're busy doing AA) just ask and the Amiga community can help

**Comment by Pyrdacor** [comment]
Sorry I lost track of this. I already invested much time in this but couldn't find the cause. Maybe you could ask the community for help on that? I ran out of ideas unfortunately.

**Comment by a1exh** [comment]
Can you remember if the crash is in :

Ambermoon BOOT1

or 

Ambermoon_install

**Comment by Pyrdacor** [comment]
Yes I think it works when running Ambermoon_install from workbench. I am not even sure if it is related to those files. There is another shell boot script on disk A. Maybe it just has not all files in it? I will check tomorrow in more detail.
